# rubygems
# npms

- name: Install nodejs and npm on Fedora
  package: name=nodejs state=present
  become_user: root
  when: (ansible_distribution == "Fedora")

- name: Install NodeJS packages
  npm: name={{ item }} state=present global=yes
  with_items: npm_packages
  tags: pkg

