---
app_folder: "{{ lookup('env','HOME') }}/Apps"
app_folder_temp: "{{ app_folder }}/temp"

versions:
  ant: 1.9.7
  maven: 3.3.9

install_opts:
  ant: False
  maven: False
  jdk7: False
  jdk8: False
  default_jdk: jdk7
  npm: False
  gems: False
  thrift: True

pip_packages:
  - virtualenv

rubygems:
  - sass
  - fpm

npm_packages:
  - bower
  - grunt-cli

fedora_packages:
  - ack
  - atop
  - autofs
  - conky
  - curl
  - dconf-editor
  - git
  - glances
  - gnome-tweak-tool
  - google-chrome-stable
  - hddtemp
  - htop
  - iotop
  - nmap
  - openssh-server
  - openssl-devel
  - glances
  - rubygems
  - shutter
  - system-storage-manager
  - tree
  - VirtualBox-5.0
  - zsh
  - flash-plugin
  - alsa-plugins-pulseaudio
  - libcurl
  - libselinux-python
